-- =============================================================
-- DATA.SQL - Du lieu mau cho QL_RAP_PHIM
-- Dong bo voi DataInitializer.java (nguon du lieu chinh, chay tu dong
-- khi app khoi dong voi DB rong). File nay chi de tham khao / chay tay
-- qua SQL*Plus hoac SQL Developer khi can khoi tao thu cong.
-- Su dung EXCEPTION WHEN DUP_VAL_ON_INDEX de tranh loi khi chay lai.
-- QUAN TRONG: chay bang UTF-8 client (vd: sqlplus voi NLS_LANG phu hop)
-- de tranh loi font tieng Viet.
-- =============================================================

-- RAP CHIEU (4 rap)
BEGIN
    INSERT INTO RAP_CHIEU VALUES ('R001', N'UTC Cinema Hà Nội', N'123 Nguyễn Trãi, Thanh Xuân, Hà Nội', '0241234567');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN
    INSERT INTO RAP_CHIEU VALUES ('R002', N'UTC Cinema HCM', N'456 Lê Văn Việt, Quận 9, TP.HCM', '0281234567');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN
    INSERT INTO RAP_CHIEU VALUES ('R003', N'UTC Cinema Đà Nẵng', N'789 Nguyễn Văn Linh, Đà Nẵng', '0236123456');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN
    INSERT INTO RAP_CHIEU VALUES ('R004', N'UTC Cinema Cần Thơ', N'321 30 Tháng 4, Ninh Kiều, Cần Thơ', '0292123456');
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

-- PHONG CHIEU
BEGIN INSERT INTO PHONG_CHIEU VALUES ('P001', 'R001', N'Phòng 1', N'2D', 80); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHONG_CHIEU VALUES ('P002', 'R001', N'Phòng 2', N'3D', 60); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHONG_CHIEU VALUES ('P003', 'R001', N'Phòng VIP', N'4DX', 40); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHONG_CHIEU VALUES ('P004', 'R002', N'Phòng 1', N'2D', 100); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHONG_CHIEU VALUES ('P005', 'R003', N'Phòng 1', N'IMAX', 120); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

-- GHE cho P001 (5 hang x 8-10 ghe = 48 ghe). Cac phong khac dung generate_seats.sql
-- Hang A (thuong)
BEGIN INSERT INTO GHE VALUES ('G001', 'P001', 'A', 1, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G002', 'P001', 'A', 2, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G003', 'P001', 'A', 3, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G004', 'P001', 'A', 4, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G005', 'P001', 'A', 5, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G006', 'P001', 'A', 6, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G007', 'P001', 'A', 7, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G008', 'P001', 'A', 8, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G009', 'P001', 'A', 9, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G010', 'P001', 'A', 10, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
-- Hang B (thuong)
BEGIN INSERT INTO GHE VALUES ('G011', 'P001', 'B', 1, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G012', 'P001', 'B', 2, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G013', 'P001', 'B', 3, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G014', 'P001', 'B', 4, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G015', 'P001', 'B', 5, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G016', 'P001', 'B', 6, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G017', 'P001', 'B', 7, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G018', 'P001', 'B', 8, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G019', 'P001', 'B', 9, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G020', 'P001', 'B', 10, N'Thường', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
-- Hang C (VIP)
BEGIN INSERT INTO GHE VALUES ('G021', 'P001', 'C', 1, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G022', 'P001', 'C', 2, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G023', 'P001', 'C', 3, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G024', 'P001', 'C', 4, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G025', 'P001', 'C', 5, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G026', 'P001', 'C', 6, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G027', 'P001', 'C', 7, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G028', 'P001', 'C', 8, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G029', 'P001', 'C', 9, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G030', 'P001', 'C', 10, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
-- Hang D (VIP)
BEGIN INSERT INTO GHE VALUES ('G031', 'P001', 'D', 1, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G032', 'P001', 'D', 2, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G033', 'P001', 'D', 3, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G034', 'P001', 'D', 4, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G035', 'P001', 'D', 5, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G036', 'P001', 'D', 6, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G037', 'P001', 'D', 7, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G038', 'P001', 'D', 8, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G039', 'P001', 'D', 9, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G040', 'P001', 'D', 10, N'VIP', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
-- Hang E (Doi)
BEGIN INSERT INTO GHE VALUES ('G041', 'P001', 'E', 1, N'Đôi', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G042', 'P001', 'E', 2, N'Đôi', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G043', 'P001', 'E', 3, N'Đôi', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G044', 'P001', 'E', 4, N'Đôi', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G045', 'P001', 'E', 5, N'Đôi', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G046', 'P001', 'E', 6, N'Đôi', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G047', 'P001', 'E', 7, N'Đôi', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO GHE VALUES ('G048', 'P001', 'E', 8, N'Đôi', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

-- THE LOAI
BEGIN INSERT INTO THE_LOAI VALUES ('TL001', N'Hành động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO THE_LOAI VALUES ('TL002', N'Hài hước'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO THE_LOAI VALUES ('TL003', N'Kinh dị'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO THE_LOAI VALUES ('TL004', N'Tình cảm'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO THE_LOAI VALUES ('TL005', N'Hoạt hình'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO THE_LOAI VALUES ('TL006', N'Khoa học viễn tưởng'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO THE_LOAI VALUES ('TL007', N'Phiêu lưu'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO THE_LOAI VALUES ('TL008', N'Tâm lý'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

-- PHIM (5 phim mau)
BEGIN INSERT INTO PHIM VALUES ('PH001', N'Avengers: Secret Wars', 150, N'Joe Russo', 'T13', DATE'2026-05-01', N'Đang chiếu', NULL, N'Cuộc chiến cuối cùng của các siêu anh hùng.'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHIM VALUES ('PH002', N'Lật Mặt 8', 120, N'Lý Hải', 'P', DATE'2026-04-15', N'Đang chiếu', NULL, N'Bộ phim hài hành động đặc sắc của đạo diễn Lý Hải.'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHIM VALUES ('PH003', N'Inside Out 3', 95, N'Pete Docter', 'P', DATE'2026-06-20', N'Sắp chiếu', NULL, N'Hành trình khám phá cảm xúc của Riley.'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHIM VALUES ('PH004', N'Venom: The Last Dance', 110, N'Kelly Marcel', 'T16', DATE'2026-03-10', N'Đang chiếu', NULL, N'Cuộc phiêu lưu cuối cùng của Eddie Brock và Venom.'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHIM VALUES ('PH005', N'Moana 2', 100, N'David Derrick Jr.', 'P', DATE'2026-07-01', N'Sắp chiếu', NULL, N'Moana trở lại trong hành trình mới khám phá đại dương.'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

-- PHIM THE LOAI
BEGIN INSERT INTO PHIM_THE_LOAI VALUES ('PH001', 'TL001'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHIM_THE_LOAI VALUES ('PH001', 'TL006'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHIM_THE_LOAI VALUES ('PH002', 'TL002'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHIM_THE_LOAI VALUES ('PH002', 'TL004'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHIM_THE_LOAI VALUES ('PH003', 'TL002'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHIM_THE_LOAI VALUES ('PH003', 'TL005'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHIM_THE_LOAI VALUES ('PH004', 'TL001'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHIM_THE_LOAI VALUES ('PH005', 'TL005'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO PHIM_THE_LOAI VALUES ('PH005', 'TL007'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

-- LICH CHIEU (ngay dong: 2026-06-25)
BEGIN INSERT INTO LICH_CHIEU VALUES ('LC001', 'PH001', 'P001', TIMESTAMP'2026-06-25 09:00:00', TIMESTAMP'2026-06-25 11:30:00', 85000, N'Mở bán'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO LICH_CHIEU VALUES ('LC002', 'PH002', 'P001', TIMESTAMP'2026-06-25 14:00:00', TIMESTAMP'2026-06-25 16:00:00', 75000, N'Mở bán'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO LICH_CHIEU VALUES ('LC003', 'PH001', 'P002', TIMESTAMP'2026-06-25 19:00:00', TIMESTAMP'2026-06-25 21:30:00', 120000, N'Mở bán'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

-- KHACH HANG (mat khau: "123456" -> BCrypt)
BEGIN INSERT INTO KHACH_HANG VALUES ('KH001', N'Nguyễn Văn An', '0901234567', 'an.nguyen@email.com', '$2a$10$LtJV9UvPcZQyEhiDMruo1OXrq.H7zQGIGyjbzYaM32gIdJOVXONP6', DATE'2024-01-15'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO KHACH_HANG VALUES ('KH002', N'Trần Thị Bình', '0912345678', 'binh.tran@email.com', '$2a$10$LtJV9UvPcZQyEhiDMruo1OXrq.H7zQGIGyjbzYaM32gIdJOVXONP6', DATE'2024-02-20'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO KHACH_HANG VALUES ('KH003', N'Lê Minh Cường', '0923456789', 'cuong.le@email.com', '$2a$10$LtJV9UvPcZQyEhiDMruo1OXrq.H7zQGIGyjbzYaM32gIdJOVXONP6', DATE'2024-03-10'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

-- NHAN VIEN (CHUC_VU: 'NHAN_VIEN' hoac 'QUAN_LY', TRANG_THAI: 'Hoạt động' hoac 'Đã khóa')
BEGIN INSERT INTO NHAN_VIEN VALUES ('NV001', 'R001', N'Đinh Quản Lý', 'QUAN_LY', '0211111111', 'quanly@utccinema.vn', '$2a$10$LtJV9UvPcZQyEhiDMruo1OXrq.H7zQGIGyjbzYaM32gIdJOVXONP6', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO NHAN_VIEN VALUES ('NV002', 'R001', N'Vũ Bán Vé', 'NHAN_VIEN', '0222222222', 'banve@utccinema.vn', '$2a$10$LtJV9UvPcZQyEhiDMruo1OXrq.H7zQGIGyjbzYaM32gIdJOVXONP6', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO NHAN_VIEN VALUES ('NV003', 'R002', N'Ngô Thị Lan', 'NHAN_VIEN', '0233333333', 'lan.ngo@utccinema.vn', '$2a$10$LtJV9UvPcZQyEhiDMruo1OXrq.H7zQGIGyjbzYaM32gIdJOVXONP6', N'Hoạt động'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

-- KHUYEN MAI
BEGIN INSERT INTO KHUYEN_MAI VALUES ('KM001', N'Giảm 20% dịp hè', 'PERCENT', 20, DATE'2026-06-01', DATE'2026-08-31'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO KHUYEN_MAI VALUES ('KM002', N'Giảm 50.000đ sinh viên', 'AMOUNT', 50000, DATE'2026-01-01', DATE'2026-12-31'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/
BEGIN INSERT INTO KHUYEN_MAI VALUES ('KM003', N'Flash sale cuối tuần', 'PERCENT', 30, DATE'2026-06-14', DATE'2026-08-31'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
/

COMMIT
/
