-- =============================================================
-- SCHEMA: QL_RAP_PHIM
-- Script khoi tao toan bo co so du lieu
-- Tat ca bang duoc tao trong schema QL_RAP_PHIM de khop voi
-- @Table(schema = "QL_RAP_PHIM") trong cac JPA entity
-- Oracle DDL tu dong COMMIT, khong can lenh COMMIT cuoi file
-- =============================================================

-- 0. Tao user/schema QL_RAP_PHIM neu chua ton tai, roi grant quyen
BEGIN
    EXECUTE IMMEDIATE 'CREATE USER QL_RAP_PHIM IDENTIFIED BY ql_rap_phim_pw';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -1920 THEN NULL; ELSE RAISE; END IF;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, DBA TO QL_RAP_PHIM';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 1. BANG RAP CHIEU
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE QL_RAP_PHIM.RAP_CHIEU (
        MA_RAP       VARCHAR2(10) PRIMARY KEY,
        TEN_RAP      NVARCHAR2(100) NOT NULL,
        DIA_CHI      NVARCHAR2(200) NOT NULL,
        SDT          VARCHAR2(15),
        CONSTRAINT UK_RAP_SDT UNIQUE (SDT)
    )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 2. BANG PHONG CHIEU
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE QL_RAP_PHIM.PHONG_CHIEU (
        MA_PHONG     VARCHAR2(10) PRIMARY KEY,
        MA_RAP       VARCHAR2(10) NOT NULL,
        TEN_PHONG    NVARCHAR2(50) NOT NULL,
        LOAI_PHONG   NVARCHAR2(30),
        SUC_CHUA     NUMBER(4) NOT NULL,
        CONSTRAINT FK_PHONG_RAP FOREIGN KEY (MA_RAP) REFERENCES QL_RAP_PHIM.RAP_CHIEU(MA_RAP),
        CONSTRAINT CK_PHONG_SUCCHUA CHECK (SUC_CHUA > 0)
    )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 3. BANG GHE
BEGIN
    EXECUTE IMMEDIATE q'[
    CREATE TABLE QL_RAP_PHIM.GHE (
        MA_GHE       VARCHAR2(10) PRIMARY KEY,
        MA_PHONG     VARCHAR2(10) NOT NULL,
        HANG_GHE     VARCHAR2(5) NOT NULL,
        SO_GHE       NUMBER(3) NOT NULL,
        LOAI_GHE     NVARCHAR2(30) DEFAULT N'Thường',
        TRANG_THAI   NVARCHAR2(30) DEFAULT N'Hoạt động',
        CONSTRAINT FK_GHE_PHONG FOREIGN KEY (MA_PHONG) REFERENCES QL_RAP_PHIM.PHONG_CHIEU(MA_PHONG),
        CONSTRAINT UK_GHE_PHONG UNIQUE (MA_PHONG, HANG_GHE, SO_GHE),
        CONSTRAINT CK_GHE_TRANGTHAI CHECK (TRANG_THAI IN (N'Hoạt động', N'Bảo trì'))
    )]';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 4. BANG THE LOAI
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE QL_RAP_PHIM.THE_LOAI (
        MA_THE_LOAI  VARCHAR2(10) PRIMARY KEY,
        TEN_THE_LOAI NVARCHAR2(80) NOT NULL,
        CONSTRAINT UK_THELOAI_TEN UNIQUE (TEN_THE_LOAI)
    )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 5. BANG PHIM
BEGIN
    EXECUTE IMMEDIATE q'[
    CREATE TABLE QL_RAP_PHIM.PHIM (
        MA_PHIM          VARCHAR2(10) PRIMARY KEY,
        TEN_PHIM         NVARCHAR2(150) NOT NULL,
        THOI_LUONG       NUMBER(4) NOT NULL,
        DAO_DIEN         NVARCHAR2(100),
        DO_TUOI          VARCHAR2(10),
        NGAY_KHOI_CHIEU  DATE,
        TRANG_THAI       NVARCHAR2(30) DEFAULT N'Đang chiếu',
        ANH_POSTER       VARCHAR2(200),
        MO_TA            NVARCHAR2(2000),
        CONSTRAINT CK_PHIM_THOILUONG CHECK (THOI_LUONG > 0),
        CONSTRAINT CK_PHIM_DOTUOI CHECK (DO_TUOI IN ('P','K','T13','T16','T18') OR DO_TUOI IS NULL)
    )]';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 6. BANG TRUNG GIAN PHIM - THE LOAI
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE QL_RAP_PHIM.PHIM_THE_LOAI (
        MA_PHIM      VARCHAR2(10) NOT NULL,
        MA_THE_LOAI  VARCHAR2(10) NOT NULL,
        CONSTRAINT PK_PHIM_THE_LOAI PRIMARY KEY (MA_PHIM, MA_THE_LOAI),
        CONSTRAINT FK_PTL_PHIM FOREIGN KEY (MA_PHIM) REFERENCES QL_RAP_PHIM.PHIM(MA_PHIM),
        CONSTRAINT FK_PTL_THELOAI FOREIGN KEY (MA_THE_LOAI) REFERENCES QL_RAP_PHIM.THE_LOAI(MA_THE_LOAI)
    )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 7. BANG LICH CHIEU
BEGIN
    EXECUTE IMMEDIATE q'[
    CREATE TABLE QL_RAP_PHIM.LICH_CHIEU (
        MA_LICH             VARCHAR2(10) PRIMARY KEY,
        MA_PHIM             VARCHAR2(10) NOT NULL,
        MA_PHONG            VARCHAR2(10) NOT NULL,
        THOI_GIAN_BAT_DAU   TIMESTAMP NOT NULL,
        THOI_GIAN_KET_THUC  TIMESTAMP NOT NULL,
        GIA_VE              NUMBER(12,2) NOT NULL,
        TRANG_THAI          NVARCHAR2(30) DEFAULT N'Mở bán',
        CONSTRAINT FK_LICH_PHIM FOREIGN KEY (MA_PHIM) REFERENCES QL_RAP_PHIM.PHIM(MA_PHIM),
        CONSTRAINT FK_LICH_PHONG FOREIGN KEY (MA_PHONG) REFERENCES QL_RAP_PHIM.PHONG_CHIEU(MA_PHONG),
        CONSTRAINT CK_LICH_GIA CHECK (GIA_VE >= 0),
        CONSTRAINT CK_LICH_THOIGIAN CHECK (THOI_GIAN_KET_THUC > THOI_GIAN_BAT_DAU)
    )]';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 8. BANG KHACH HANG
BEGIN
    EXECUTE IMMEDIATE '
    CREATE TABLE QL_RAP_PHIM.KHACH_HANG (
        MA_KH        VARCHAR2(10) PRIMARY KEY,
        HO_TEN       NVARCHAR2(100) NOT NULL,
        SDT          VARCHAR2(15) NOT NULL,
        EMAIL        VARCHAR2(100),
        MAT_KHAU     VARCHAR2(200),
        NGAY_DANG_KY DATE DEFAULT SYSDATE,
        CONSTRAINT UK_KH_SDT UNIQUE (SDT),
        CONSTRAINT UK_KH_EMAIL UNIQUE (EMAIL)
    )';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 9. BANG NHAN VIEN
BEGIN
    EXECUTE IMMEDIATE q'[
    CREATE TABLE QL_RAP_PHIM.NHAN_VIEN (
        MA_NV        VARCHAR2(10) PRIMARY KEY,
        MA_RAP       VARCHAR2(10) NOT NULL,
        HO_TEN       NVARCHAR2(100) NOT NULL,
        CHUC_VU      NVARCHAR2(50),
        SDT          VARCHAR2(15),
        EMAIL        VARCHAR2(100),
        MAT_KHAU     VARCHAR2(200),
        TRANG_THAI   NVARCHAR2(30) DEFAULT N'Hoạt động',
        CONSTRAINT FK_NV_RAP FOREIGN KEY (MA_RAP) REFERENCES QL_RAP_PHIM.RAP_CHIEU(MA_RAP),
        CONSTRAINT UK_NV_EMAIL UNIQUE (EMAIL),
        CONSTRAINT CK_NV_TRANGTHAI CHECK (TRANG_THAI IN (N'Hoạt động', N'Đã khóa'))
    )]';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 9b. Bo sung cot TRANG_THAI cho DB da tao truoc do (khong co cot nay)
BEGIN
    EXECUTE IMMEDIATE q'[
    ALTER TABLE QL_RAP_PHIM.NHAN_VIEN ADD (
        TRANG_THAI NVARCHAR2(30) DEFAULT N'Hoạt động'
        CONSTRAINT CK_NV_TRANGTHAI CHECK (TRANG_THAI IN (N'Hoạt động', N'Đã khóa'))
    )]';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -1430 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 10. BANG KHUYEN MAI
BEGIN
    EXECUTE IMMEDIATE q'[
    CREATE TABLE QL_RAP_PHIM.KHUYEN_MAI (
        MA_KM          VARCHAR2(10) PRIMARY KEY,
        TEN_KM         NVARCHAR2(120) NOT NULL,
        LOAI_GIAM      VARCHAR2(20) NOT NULL,
        GIA_TRI        NUMBER(12,2) NOT NULL,
        NGAY_BAT_DAU   DATE,
        NGAY_KET_THUC  DATE,
        CONSTRAINT CK_KM_LOAI CHECK (LOAI_GIAM IN ('PERCENT','AMOUNT')),
        CONSTRAINT CK_KM_GIATRI CHECK (GIA_TRI >= 0)
    )]';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 11. BANG DAT VE
BEGIN
    EXECUTE IMMEDIATE q'[
    CREATE TABLE QL_RAP_PHIM.DAT_VE (
        MA_DAT       VARCHAR2(10) PRIMARY KEY,
        MA_KH        VARCHAR2(10) NOT NULL,
        MA_NV        VARCHAR2(10),
        MA_KM        VARCHAR2(10),
        NGAY_DAT     TIMESTAMP DEFAULT SYSTIMESTAMP,
        TONG_TIEN    NUMBER(12,2) DEFAULT 0,
        TRANG_THAI   NVARCHAR2(30) DEFAULT N'Chờ thanh toán',
        CONSTRAINT FK_DAT_KH FOREIGN KEY (MA_KH) REFERENCES QL_RAP_PHIM.KHACH_HANG(MA_KH),
        CONSTRAINT FK_DAT_NV FOREIGN KEY (MA_NV) REFERENCES QL_RAP_PHIM.NHAN_VIEN(MA_NV),
        CONSTRAINT FK_DAT_KM FOREIGN KEY (MA_KM) REFERENCES QL_RAP_PHIM.KHUYEN_MAI(MA_KM),
        CONSTRAINT CK_DAT_TONGTIEN CHECK (TONG_TIEN >= 0)
    )]';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 12. BANG VE
BEGIN
    EXECUTE IMMEDIATE q'[
    CREATE TABLE QL_RAP_PHIM.VE (
        MA_VE        VARCHAR2(10) PRIMARY KEY,
        MA_DAT       VARCHAR2(10) NOT NULL,
        MA_LICH      VARCHAR2(10) NOT NULL,
        MA_GHE       VARCHAR2(10) NOT NULL,
        GIA_VE       NUMBER(12,2) NOT NULL,
        TRANG_THAI   NVARCHAR2(30) DEFAULT N'Đã đặt',
        CONSTRAINT FK_VE_DAT FOREIGN KEY (MA_DAT) REFERENCES QL_RAP_PHIM.DAT_VE(MA_DAT),
        CONSTRAINT FK_VE_LICH FOREIGN KEY (MA_LICH) REFERENCES QL_RAP_PHIM.LICH_CHIEU(MA_LICH),
        CONSTRAINT FK_VE_GHE FOREIGN KEY (MA_GHE) REFERENCES QL_RAP_PHIM.GHE(MA_GHE),
        CONSTRAINT UK_VE_LICH_GHE UNIQUE (MA_LICH, MA_GHE),
        CONSTRAINT CK_VE_GIA CHECK (GIA_VE >= 0)
    )]';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/

-- 13. BANG THANH TOAN
BEGIN
    EXECUTE IMMEDIATE q'[
    CREATE TABLE QL_RAP_PHIM.THANH_TOAN (
        MA_TT        VARCHAR2(10) PRIMARY KEY,
        MA_DAT       VARCHAR2(10) NOT NULL,
        SO_TIEN      NUMBER(12,2) NOT NULL,
        NGAY_TT      TIMESTAMP DEFAULT SYSTIMESTAMP,
        PHUONG_THUC  NVARCHAR2(50),
        TRANG_THAI   NVARCHAR2(30) DEFAULT N'Thành công',
        CONSTRAINT FK_TT_DAT FOREIGN KEY (MA_DAT) REFERENCES QL_RAP_PHIM.DAT_VE(MA_DAT),
        CONSTRAINT CK_TT_SOTIEN CHECK (SO_TIEN >= 0)
    )]';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF;
END;
/
